"""empty message

Revision ID: 7def9d0fe456
Revises: 
Create Date: 2022-06-14 16:09:22.977709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7def9d0fe456'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('time_meet', sa.String(), nullable=True))
    op.add_column('message', sa.Column('location_meet', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'location_meet')
    op.drop_column('message', 'time_meet')
    # ### end Alembic commands ###
